#!/usr/bin/env python
# This file is automatically generated by pywf script
# based on the content in pyproject.toml file

__version__ = "2.3.2"
__short_description__ = "Objective Oriented Interface for AWS S3, similar to pathlib."
__license__ = "Apache License 2.0"
__author__ = "Sanhe Hu"
__author_email__ = "sanhehu@amazon.com"
__maintainer__ = "Sanhe Hu"
__maintainer_email__ = "husanhe@gmail.com"

# run this script to print out the version number
if __name__ == "__main__":  # pragma: no cover
    print(__version__)
